# hyper-parameters
batch_size: 32
lr: 1e-3
dr: 5e-4
num_epochs: 5

# model
model: baseline
num_filters: 32

# experiment
exp_dir: exp
exp_name: baseline_test

# evaluation
eval_dir: eval
eval_name: baseline_eval

# dataset
data_path: data
